### ISSUE TITLE
Re-collimate reference beam before it reaches the hologram

### ISSUE THREAD

**Issue by waldyrious** [TiagoLeite07/ComputerGeneratedHolography_VirtualLab#2]
The reference beam should be a planar wavefront. There needs to be a large convergent lens that stops the expansion after the first divergent lens that turns the straight beam into a spherical wave.

This construction is called a beam expander and looks something like this:
![Beam expander](http://www.edmundoptics.com/images/articles/4a.gif)

**Comment by TiagoLeite07** [comment]
Thanks.

Done.

**Comment by waldyrious** [comment]
Thanks for the quick reaction ;)

Btw, it's usually nice to mention the commit that fixes an issue when closing it, for future reference. E.g. 797474f

**Comment by TiagoLeite07** [comment]
I changed the amplifier geometry too.

commit: https://github.com/TiagoLeite07/cgh-lab/commit/d16ba167f166ae1b43df76d2461dbed65d90c3b7

**Comment by waldyrious** [comment]
Nice. Btw, here's a reference for the physically correct lens shapes, in case you decide to make it more realistic: https://en.wikipedia.org/wiki/Lens_%28optics%29#Types_of_simple_lenses
