### ISSUE TITLE
Make beam splitter transparent

### ISSUE THREAD

**Issue by waldyrious** [TiagoLeite07/ComputerGeneratedHolography_VirtualLab#3]
It should look something like this:

![](http://physics.aps.org/assets/35bc53c6-83d0-4df3-b3d3-b7f87cb59fea/e21_1_medium.jpg)

or these:

![](https://upload.wikimedia.org/wikipedia/commons/1/15/Bamsplitter-2.jpg)

**Comment by TiagoLeite07** [comment]
Thanks.

Done.

**Comment by waldyrious** [comment]
:+1:
